
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.b7f2.ws.kike.generatebykike.service;

import com.b7f2.ws.kike.generatebykike.bean.BeanLogin;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-27T13:20:45.178+02:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "ImplLoginService",
                      portName = "ImplLogin",
                      targetNamespace = "http://service.ws.b7f2.com",
                      wsdlLocation = "https://www.czidconnect.es:8443/messenger/services/ImplLogin?wsdl",
                      endpointInterface = "ImplLogin")
                      
public class ImplLoginImpl implements ImplLogin {

    private static final Logger LOG = Logger.getLogger(ImplLoginImpl.class.getName());

    /* (non-Javadoc)
     * @see ImplLogin#validaLogin(BeanLogin  obj )*
     */
    public BeanLogin validaLogin(BeanLogin obj) {
        LOG.info("Executing operation validaLogin");
        System.out.println(obj);
        try {
            BeanLogin _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
