
package com.mingorance.soap.client.zaragoza.axesor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QualitasWebServicesSoap", targetNamespace = "http://www.axesor.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QualitasWebServicesSoap {


    /**
     * Procesa la solicitud
     * 
     * @param peticionXml
     * @param nombreUsuario
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AtenderPeticion", action = "http://www.axesor.es/AtenderPeticion")
    @WebResult(name = "AtenderPeticionResult", targetNamespace = "http://www.axesor.es/")
    @RequestWrapper(localName = "AtenderPeticion", targetNamespace = "http://www.axesor.es/", className = "AtenderPeticion")
    @ResponseWrapper(localName = "AtenderPeticionResponse", targetNamespace = "http://www.axesor.es/", className = "AtenderPeticionResponse")
    public String atenderPeticion(
            @WebParam(name = "nombreUsuario", targetNamespace = "http://www.axesor.es/")
                    String nombreUsuario,
            @WebParam(name = "pwd", targetNamespace = "http://www.axesor.es/")
                    String pwd,
            @WebParam(name = "peticionXml", targetNamespace = "http://www.axesor.es/")
                    String peticionXml);

}
