
package com.mingorance.soap.client.zaragoza;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImplLoginService", targetNamespace = "http://service.ws.b7f2.com", wsdlLocation = "https://www.czidconnect.es:8443/messenger/services/ImplLogin?wsdl")
public class ImplLoginService
    extends Service
{

    private final static URL IMPLLOGINSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMPLLOGINSERVICE_EXCEPTION;
    private final static QName IMPLLOGINSERVICE_QNAME = new QName("http://service.ws.b7f2.com", "ImplLoginService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.czidconnect.es:8443/messenger/services/ImplLogin?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMPLLOGINSERVICE_WSDL_LOCATION = url;
        IMPLLOGINSERVICE_EXCEPTION = e;
    }

    public ImplLoginService() {
        super(__getWsdlLocation(), IMPLLOGINSERVICE_QNAME);
    }

    public ImplLoginService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMPLLOGINSERVICE_QNAME, features);
    }

    public ImplLoginService(URL wsdlLocation) {
        super(wsdlLocation, IMPLLOGINSERVICE_QNAME);
    }

    public ImplLoginService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMPLLOGINSERVICE_QNAME, features);
    }

    public ImplLoginService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImplLoginService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImplLogin
     */
    @WebEndpoint(name = "ImplLogin")
    public ImplLogin getImplLogin() {
        return super.getPort(new QName("http://service.ws.b7f2.com", "ImplLogin"), ImplLogin.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImplLogin
     */
    @WebEndpoint(name = "ImplLogin")
    public ImplLogin getImplLogin(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.b7f2.com", "ImplLogin"), ImplLogin.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMPLLOGINSERVICE_EXCEPTION!= null) {
            throw IMPLLOGINSERVICE_EXCEPTION;
        }
        return IMPLLOGINSERVICE_WSDL_LOCATION;
    }

}
