
package com.mingorance.soap.client.zaragoza;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImplLogin", targetNamespace = "http://service.ws.b7f2.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImplLogin {


    /**
     * 
     * @param obj
     * @return
     *     returns com.mingorance.soap.client.zaragoza.BeanLogin
     */
    @WebMethod
    @WebResult(name = "validaLoginReturn", targetNamespace = "http://service.ws.b7f2.com")
    @RequestWrapper(localName = "validaLogin", targetNamespace = "http://service.ws.b7f2.com", className = "com.mingorance.soap.client.zaragoza.ValidaLogin")
    @ResponseWrapper(localName = "validaLoginResponse", targetNamespace = "http://service.ws.b7f2.com", className = "com.mingorance.soap.client.zaragoza.ValidaLoginResponse")
    public BeanLogin validaLogin(
            @WebParam(name = "obj", targetNamespace = "http://service.ws.b7f2.com")
                    BeanLogin obj);

}
