
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.b7f2.ws.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-27T13:20:45.178+02:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "ImplLoginService",
                      portName = "ImplLogin",
                      targetNamespace = "http://service.ws.b7f2.com",
                      wsdlLocation = "https://www.czidconnect.es:8443/messenger/services/ImplLogin?wsdl",
                      endpointInterface = "com.b7f2.ws.service.ImplLogin")
                      
public class ImplLoginImpl implements ImplLogin {

    private static final Logger LOG = Logger.getLogger(ImplLoginImpl.class.getName());

    /* (non-Javadoc)
     * @see com.b7f2.ws.service.ImplLogin#validaLogin(com.b7f2.ws.bean.BeanLogin  obj )*
     */
    public com.b7f2.ws.bean.BeanLogin validaLogin(com.b7f2.ws.bean.BeanLogin obj) { 
        LOG.info("Executing operation validaLogin");
        System.out.println(obj);
        try {
            com.b7f2.ws.bean.BeanLogin _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
